name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4 which uses Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4 which uses Node.js 20
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install unittest

    - name: Run tests
      run: |
        python -m unittest discover tests


