name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4 to ensure it's using the latest version

    - name: Run tests
      run: |
        chmod +x hello.sh
        chmod +x tests/test_hello.sh
        ./tests/test_hello.sh
